apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-nginx
  name: gitops-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitops-nginx
  type: LoadBalancer
